name: whatelse_server
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  lints: ^2.0.0

dependencies:
  async: ^2.11.0
  crypto: ^3.0.2
  equatable: ^2.0.5
  fixnum: ^1.1.0
  grpc: ^3.1.0
  json_annotation: ^4.8.0
  logger: ^1.3.0
  orm: ^3.2.6
  protobuf: ^2.1.0
  redis: ^3.1.0
  synchronized: ^3.0.1
  test: ^1.24.1
  yaml: ^3.1.1
